"""Changed a column name from Post.datetime to Post.timestamp

Revision ID: 84db2e98e36b
Revises: 473d12f23ee0
Create Date: 2021-07-28 21:41:10.778379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84db2e98e36b'
down_revision = '473d12f23ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_index('ix_post_datetime', table_name='post')
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_column('post', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('datetime', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.create_index('ix_post_datetime', 'post', ['datetime'], unique=False)
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
